image: cypress/browsers:node18.12.0-chrome114-ff113

stages: [test, deploy]

cache:
  paths:
    - node_modules/

variables:
  # garanta saída não-interativa em ambientes CI
  CI: "true"

# 1) Executa testes e gera o Allure
cypress_tests:
  stage: test
  script:
    - npm ci
    - npx cypress verify
    - npx cypress run
    # gerar relatório Allure (precisa Java)
    - apt-get update && apt-get install -y openjdk-11-jre-headless
    - npx allure generate --clean allure-results -o allure-report
  artifacts:
    when: always
    expire_in: 7 days
    paths:
      - allure-results
      - allure-report
      - cypress/screenshots
      - cypress/videos

# 2) Publica Allure no GitLab Pages
pages:
  stage: deploy
  needs: ["cypress_tests"]   # baixa artifacts do job de testes
  script:
    - mkdir -p public
    - cp -r allure-report/* public/
  artifacts:
    paths:
      - public
  only:
    - main    # publique só na branch principal
